### ISSUE TITLE
Push Notifications TODO

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#1346]
whats missing:
* [ ] notifications about onchain addresses transactions 
* [ ] pass batch addresses for HD wallets (currently only one address is passed to groundcontrol, when you tap Receive)
* [ ] unsubscribe from addresses when wallet is deleted
* [ ] splitting notifications into categories so user can unsubscribe from specific categories (like, unsub from price movements)
* [ ] theres no metadata per token in database yet (current bw version, last online, lang)
* [ ] theres no screen in settings where user can check if he allowed pushes, also where user can disable certain categories of pushes
* [ ] no localization engine yet, so texts for notifications are currently hardcoded in english
* [ ] push notification payload is _not_ processed in the app (app should figure out which specific wallet is related to push and update it)

**Comment by Overtorment** [comment]
https://github.com/BlueWallet/BlueWallet/pull/1467

**Comment by thenewbug** [comment]
I also noted about an issue with the notification query when OS does not have google services or notifications. (Android 10 open source builds like GrapheneOS or CopperheadOS) 

https://github.com/BlueWallet/BlueWallet/issues/1839
