### ISSUE TITLE
[BIP84] Add HD Segwit (bech32) wallet support

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#172]
Also, I'm thinking about making it a default wallet, and build all advanced features (cpfp, rbf, batching, signing) only for this wallet.

https://iancoleman.io/bip39/
https://github.com/bitcoin/bips/blob/master/bip-0084.mediawiki

**Comment by Overtorment** [comment]
We have a somewhat complete test suite for HD Segwit p2sh wallets. Better start with tests for new wallet

**Comment by Overtorment** [comment]
TODO:

* [ ] Create class
* [ ] TDD: test vector: add tests for internal/externall address gen
* [ ] TDD: add test for fetch balance
* [ ] implement fetch balance (Electrum)
* [ ] TDD: add test for fetch transactions
* [ ] implement fetch transactions (Electrum)
* [ ] TDD: add tests for fetch UTXO
* [ ] imlement fetch UTXO
* [ ] implement sign tx (with batching)

**Comment by Overtorment** [comment]
WIP PR https://github.com/BlueWallet/BlueWallet/pull/352
